name: xwebrtc
channels:
  - conda-forge
dependencies:
  # Widgets 
  - xwebrtc=0.4.1
  - xwidgets=0.16.1
  - widgetsnbextension >=3.0.0
  - ipywebrtc=0.4.1
  # Xtensor
  - xtensor-io=0.7.0
  - xtensor-fftw=0.2.5
  # C++ kernel
  - xeus-cling=0.4.11
