name: xwebrtc
channels:
  - QuantStack
  - conda-forge
dependencies:
  - xwebrtc=0.4.0
  - xwidgets=0.16.0
  - xeus-cling=0.4.10
  - ipywebrtc=0.4.1
  - notebook >=5.4
  - widgetsnbextension >=3.0.0
  - xtensor-io=0.7.0
  - xtensor-fftw=0.2.5
  - openimageio=1.8.9
